apis/urls.py
from django.urls import include, path
from rest_framework import routers

from apis import views

router = routers.SimpleRouter()
router.register(r"doctors", views.DoctorViewSet)
router.register(r"pets", views.PetViewSet)
router.register(r"clinics", views.VeterinaryViewSet)
router.register(r"clinics-instance", views.VeterinaryInstanceViewSet)
router.register(r"specialties", views.SpecialtiesViewSet)
router.register(r"services", views.ServiceViewSet)
router.register(r"users", views.UserViewSet)


urlpatterns = [
    path("", include(router.urls)),
]

booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from booking import views

urlpatterns = [
    # create
    path(
        "bookings/new/",
        views.VeterinaryInstanceCreate.as_view(),
        name="veterinary-instance-create",
    ),
    path("doctors/new/", views.DoctorCreate.as_view(), name="doctor-create"),
    path(
        "veterinarians/new/",
        views.VeterinaryCreate.as_view(),
        name="veterinary-create",
    ),
    path("pets/new/", views.PetCreate.as_view(), name="pet-create"),
    path(
        "specialties/new/",
        views.SpecialtiesCreate.as_view(),
        name="specialties-create",
    ),
    path("services/new/", views.CreateService.as_view(), name="service-create"),
    # update
    path(
        "bookings/<uuid:pk>/update/",
        views.VeterinaryInstanceUpdate.as_view(),
        name="veterinary-instance-update",
    ),
    path(
        "doctors/<int:pk>/update/", views.DoctorUpdate.as_view(), name="doctor-update"
    ),
    path(
        "veterinarians/<int:pk>/update/",
        views.VeterinaryUpdate.as_view(),
        name="veterinary-update",
    ),
    path("pets/<int:pk>/update/", views.PetUpdate.as_view(), name="pet-update"),
    # detail
    path("doctors/<int:pk>/", views.DoctorDetail.as_view(), name="doctor-detail"),
    path(
        "veterinarians/<int:pk>/",
        views.VeterinaryDetail.as_view(),
        name="veterinary-detail",
    ),
    path(
        "bookings/<uuid:pk>/",
        views.VeterinaryInstanceDetail.as_view(),
        name="veterinary-instance-detail",
    ),
    path("pets/<int:pk>/", views.PetDetail.as_view(), name="pet-detail"),
    # list
    path(
        "bookings/",
        views.VeterinaryInstanceList.as_view(),
        name="veterinary-instance-list",
    ),
    path("pets/", views.PetList.as_view(), name="pet-list"),
    path("veterinarians/", views.VeterinaryList.as_view(), name="veterinarians-list"),
    path("doctors/", views.DoctorList.as_view(), name="doctor-list"),
    path("", views.index, name="home"),
    path("search/", views.SearchResultsList.as_view(), name="search-results"),
    path("appointments/", views.ApppoinmentsView, name="appointment"),
    # delete
    path("pet/delete/<int:pk>/", views.PetDelete.as_view(), name="pet-delete"),
    path(
        "booking/delete/<uuid:pk>/",
        views.VeterinaryInstanceDelete.as_view(),
        name="veterinary-instance-delete",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("apis.urls")),
    path("", include("booking.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class Specialties(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]
        verbose_name = "Specialty"
        verbose_name_plural = "Specialties"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("specialties-detail", args=[str(self.id)])


class Service(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Veterinary(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    address = models.CharField(max_length=255, blank=False, null=False)
    contact_number = PhoneNumberField(blank=False, null=False)
    services = models.ManyToManyField(Service)
    image = models.ImageField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.address})"

    def get_absolute_url(self):
        return reverse("veterinary-detail", args=[str(self.id)])


class Doctor(models.Model):
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    clinic = models.ForeignKey(Veterinary, on_delete=models.CASCADE)
    specialties = models.ManyToManyField(Specialties)
    email = models.EmailField(max_length=255, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.last_name},{self.first_name}"

    def get_absolute_url(self):
        return reverse("doctor-detail", args=[str(self.id)])


class Pet(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False, null=False)
    date_birth = models.DateField()
    breed = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("pet-detail", args=[str(self.id)])


class VeterinaryInstance(models.Model):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    APPOINTMENT_STATUS = {
        PENDING: "Pending",
        APPROVED: "Approved",
        DECLINED: "Declined",
    }
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    veterinary_name = models.ForeignKey(Veterinary, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    pet_name = models.ForeignKey(Pet, on_delete=models.CASCADE)
    description = models.TextField(max_length=255, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    schedule = models.DateTimeField()
    status = models.CharField(
        max_length=10, choices=APPOINTMENT_STATUS, default="Pending"
    )

    class Meta:
        ordering = ["schedule"]

    def __str__(self):
        return f"{self.veterinary_name}"

    def get_absolute_url(self):
        return reverse("veterinary-instance-detail", args=[str(self.id)])

booking/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from booking import models


class PetCreateForm(forms.ModelForm):
    class Meta:
        model = models.Pet
        fields = ["name", "date_birth", "breed"]
        widgets = {
            "date_birth": forms.DateInput(attrs={"type": "date"}),
        }


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = models.VeterinaryInstance
        fields = ["veterinary_name", "pet_name", "description", "schedule"]
        widgets = {
            "schedule": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

    def clean_schedule(self):
        data = self.cleaned_data["schedule"]
        if data < now():
            raise ValidationError("schedule should be in the past")
        return data

booking/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from booking import forms, models


# index view
def index(request):
    available_clinics = models.Veterinary.objects.count()
    available_doctors = models.Doctor.objects.count()
    num_pets = 0
    num_appointments = 0

    if request.user.is_authenticated:
        num_pets = models.Pet.objects.filter(owner=request.user).count()
        num_appointments = models.VeterinaryInstance.objects.filter(
            owner=request.user
        ).count()

    context = {
        "available_clinics": available_clinics,
        "available_doctors": available_doctors,
        "num_pets": num_pets,
        "num_appointments": num_appointments,
    }
    return render(request, "index.html", context=context)


# staff views
def ApppoinmentsView(request):
    pending_appointments = models.VeterinaryInstance.objects.filter(status="Pending")
    approved_appointments = models.VeterinaryInstance.objects.filter(status="Approved")
    declined_appointments = models.VeterinaryInstance.objects.filter(status="Declined")

    context = {
        "pending_appointments": pending_appointments,
        "approved_appointments": approved_appointments,
        "declined_appointments": declined_appointments,
    }
    return render(request, "booking/appointments.html", context=context)


# doctor views
class DoctorCreate(LoginRequiredMixin, CreateView):
    model = models.Doctor
    fields = [
        "first_name",
        "last_name",
        "clinic",
        "specialties",
        "email",
        "phone_number",
    ]


class DoctorUpdate(LoginRequiredMixin, UpdateView):
    model = models.Doctor
    fields = ["first_name", "last_name", "specialties", "email", "phone_number"]


class DoctorDetail(DetailView):
    model = models.Doctor


class DoctorList(ListView):
    model = models.Doctor
    paginate_by = 20


# veterinary views
class VeterinaryCreate(LoginRequiredMixin, CreateView):
    model = models.Veterinary
    fields = ["name", "address", "contact_number", "services", "image"]


class VeterinaryUpdate(LoginRequiredMixin, UpdateView):
    model = models.Veterinary
    fields = ["name", "address", "contact_number", "services"]


class VeterinaryDetail(DetailView):
    model = models.Veterinary


class VeterinaryList(ListView):
    model = models.Veterinary
    paginate_by = 20


# pet views
class PetCreate(LoginRequiredMixin, CreateView):
    model = models.Pet
    form_class = forms.PetCreateForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PetUpdate(LoginRequiredMixin, UpdateView):
    model = models.Pet
    form_class = forms.PetCreateForm


class PetDetail(DetailView):
    model = models.Pet


class PetList(LoginRequiredMixin, ListView):
    model = models.Pet
    paginate_by = 20

    def get_queryset(self):
        pet_list = models.Pet.objects.filter(owner=self.request.user)
        return pet_list


class PetDelete(DeleteView):
    model = models.Pet
    success_url = reverse_lazy("pet-list")


# veterinary instance views
class VeterinaryInstanceCreate(LoginRequiredMixin, CreateView):
    model = models.VeterinaryInstance
    form_class = forms.AppointmentForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Filter pet_name field choices based on the logged-in user
        form.fields["pet_name"].queryset = models.Pet.objects.filter(
            owner=self.request.user
        )
        return form


class VeterinaryInstanceUpdate(LoginRequiredMixin, UpdateView):
    model = models.VeterinaryInstance
    fields = ["veterinary_name", "doctor", "description", "status"]


class VeterinaryInstanceDetail(DetailView):
    model = models.VeterinaryInstance


class VeterinaryInstanceList(LoginRequiredMixin, ListView):
    model = models.VeterinaryInstance
    paginate_by = 20

    def get_queryset(self):
        booking_list = models.VeterinaryInstance.objects.filter(owner=self.request.user)
        return booking_list


class VeterinaryInstanceDelete(DeleteView):
    model = models.VeterinaryInstance
    success_url = reverse_lazy("veterinary-instance-list")


# specialties views
class SpecialtiesCreate(LoginRequiredMixin, CreateView):
    model = models.Specialties
    fields = ["name"]
    success_url = reverse_lazy("specialties-create")


class SearchResultsList(ListView):
    model = models.Veterinary
    template_name = "booking/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            object_list = models.Veterinary.objects.filter(
                Q(name__icontains=query) | Q(address__icontains=query)
            )

            return object_list


# services
class CreateService(CreateView):
    model = models.Service
    fields = ["name"]
    success_url = reverse_lazy("service-create")

templates/booking/appointments.html
{% extends '_base.html' %}


{% block content %}
    <h1>Pending Appointments</h1>
    <ul>
        {% for pending in pending_appointments %}
        <li><a href="{% url 'veterinary-instance-update' pending.id %}"> {{ pending }}</a></li>
        {% empty %}
        <p>No Pending Appointments</p>
        {% endfor %}
    </ul>
    <br>
    <h1>Approved Appointments</h1>
    <ul>
        {% for approved in approved_appointments %}
        <li>{{ approved }}</li>
        {% empty %}
        <p>No Approved Appointments</p>
        {% endfor %}
    </ul>
    <br>
    <h1>Declined Appointments</h1>
    <ul>
        {% for declined in declined_appointments %}
        <li>{{ declined }}</li>
        {% empty %}
        <p>No Declined Appointments</p>
        {% endfor %}
    </ul>
{% endblock content %}
    

templates/booking/doctor_detail.html
{% extends '_base.html' %}


{% block content %}
<ul>
    <li><strong>Name: </strong>{{ doctor.last_name|capfirst }},{{ doctor.first_name|capfirst }}</li>
    <li><strong>Specialties: </strong>{% for specialty in doctor.specialties.all %} {{ specialty.name|capfirst }}{% if not forloop.last %}, {% endif %} {% endfor %}</li>
    
    {% if doctor.email %}
    <li><strong>Email: </strong>{{ doctor.email }}</li>
    {% endif %}
    
    {% if doctor.phone_number %}
    <li><strong>Phone Number: </strong>{{ doctor.phone_number }}</li>
    {% endif %}
        
</ul>

{% if perms.booking.change_doctor %}
<a class="btn btn-info" href="{% url 'doctor-update' doctor.id %}" role="button">Change</a>
{% endif %}
    
{% endblock content %}
    

templates/booking/doctor_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}
    

templates/booking/doctor_list.html
{% extends '_base.html' %}


{% block content %}

{% for doctor in doctor_list %}
<ul>
    <li><a href="{% url 'doctor-detail' doctor.id %}">{{ doctor.last_name|capfirst }},{{ doctor.first_name|capfirst }}</a></li>
</ul>
{% endfor %}
    
    
{% endblock content %}
    

templates/booking/pet_confirm_delete.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to remove "{{ object }}"?</p>
    {{ form|crispy }}
    <a class="btn btn-primary" href="{% url 'pet-list' %}" role="button">Cancel</a>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock content %}
    

templates/booking/pet_detail.html
{% extends '_base.html' %}


{% block content %}
<ul>
    <li><strong>Name: </strong>{{ pet.name|capfirst }}</li>
    <li><strong>Birthday: </strong>{{ pet.date_birth }}</li>
    <li><strong>Breed: </strong>{{ pet.breed|capfirst }}</li>
</ul>
<a class="btn btn-info" href="{% url 'pet-update' pet.id %}" role="button">Change</a>
<a class="btn btn-danger" href="{% url 'pet-delete' pet.id %}" role="button">Remove</a>
{% endblock content %}
    

templates/booking/pet_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}
    

templates/booking/pet_list.html
{% extends '_base.html' %}


{% block content %}

{% if user.is_authenticated %}
{% for pet in pet_list %}
<ul>
    <li><a href="{% url 'pet-detail' pet.id %}">{{ pet.name|capfirst }}</a></li>
</ul>
{% empty %}
<p>you have no registered pet</p>
<p>please register you using this <a href="{% url 'pet-create' %}">link</a></p>
{% endfor %}
{% endif %}
  
{% endblock content %}
    

templates/booking/search_results.html
{% extends '_base.html' %}


{% block content %}
<h1>Search Results</h1>

<ul>
  {% for result in object_list %}
    <li>
      <strong><a href="{% url 'veterinary-detail' result.id %}">{{ result.name }} ({{ result.address }})</a></strong>
    </li>
    {% empty %}
    <h2>No Result</h2>
  {% endfor %}
</ul>

{% endblock content %}
    

templates/booking/service_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}
    

templates/booking/specialties_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}
    

templates/booking/veterinary_detail.html
{% extends '_base.html' %}


{% block content %}
<ul>
    <li><strong>Name: </strong>{{ veterinary.name }}</li>
    <li><strong>Address: </strong>{{ veterinary.address }}</li>
    <li><strong>Contact Number: </strong>{{ veterinary.contact_number }}</li>
    <li><strong>Services: </strong>{% for service in veterinary.services.all %} {{ service|capfirst }}{% if not forloop.last %}, {% endif %}{% endfor %} </li>
    
    {% if veterinary.image %}
    <img src="{{ veterinary.image.url }}" alt="clinic image">    
    {% endif %}
        
</ul>

{% if perms.booking.change_veterinary %}
<a class="btn btn-info" href="{% url 'veterinary-update' veterinary.id %}" role="button">Change</a>
{% endif %}

{% endblock content %}
    

templates/booking/veterinaryinstance_confirm_delete.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to cancel your appointment in "{{ object }}"?</p>
    {{ form|crispy }}
    <a class="btn btn-primary" href="{% url 'veterinary-instance-list' %}" role="button">Cancel</a>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock content %}
    

templates/booking/veterinaryinstance_list.html
{% extends '_base.html' %}


{% block content %}

{% for veterinary_instance in veterinaryinstance_list %}
<ul>
<li><a href="{% url 'veterinary-instance-detail' veterinary_instance.id %}">{{ veterinary_instance.veterinary_name|capfirst }} {{ veterinary_instance.schedule }}</a></li>
</ul>
{% empty %}
<p>You have no appointment to click this <a href="{% url 'veterinary-instance-create' %}">Link</a> to add appointment</p>
{% endfor %}

    
{% endblock content %}
    