apis/urls.py
from django.urls import include, path
from rest_framework import routers

from apis import views

router = routers.SimpleRouter()
router.register(r"doctors", views.DoctorViewSet)
router.register(r"pets", views.PetViewSet)
router.register(r"clinics", views.VeterinaryViewSet)
router.register(r"clinics-instance", views.VeterinaryInstanceViewSet)
router.register(r"specialties", views.SpecialtiesViewSet)
router.register(r"services", views.ServiceViewSet)
router.register(r"users", views.UserViewSet)


urlpatterns = [
    path("", include(router.urls)),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("apis.urls")),
    path("", include("booking.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class Specialties(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]
        verbose_name = "Specialty"
        verbose_name_plural = "Specialties"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("specialties-detail", args=[str(self.id)])


class Service(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Veterinary(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    address = models.CharField(max_length=255, blank=False, null=False)
    contact_number = PhoneNumberField(blank=False, null=False)
    services = models.ManyToManyField(Service)
    image = models.ImageField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.address})"

    def get_absolute_url(self):
        return reverse("veterinary-detail", args=[str(self.id)])


class Doctor(models.Model):
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    clinic = models.ForeignKey(Veterinary, on_delete=models.CASCADE)
    specialties = models.ManyToManyField(Specialties)
    email = models.EmailField(max_length=255, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.last_name},{self.first_name}"

    def get_absolute_url(self):
        return reverse("doctor-detail", args=[str(self.id)])


class Pet(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False, null=False)
    date_birth = models.DateField()
    breed = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("pet-detail", args=[str(self.id)])


class VeterinaryInstance(models.Model):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    APPOINTMENT_STATUS = {
        PENDING: "Pending",
        APPROVED: "Approved",
        DECLINED: "Declined",
    }
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    veterinary_name = models.ForeignKey(Veterinary, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    pet_name = models.ForeignKey(Pet, on_delete=models.CASCADE)
    description = models.TextField(max_length=255, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    schedule = models.DateTimeField()
    status = models.CharField(
        max_length=10, choices=APPOINTMENT_STATUS, default="Pending"
    )

    class Meta:
        ordering = ["schedule"]

    def __str__(self):
        return f"{self.veterinary_name}"

    def get_absolute_url(self):
        return reverse("veterinary-instance-detail", args=[str(self.id)])

templates/_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title> {% block title %}Veterinary Booking{% endblock title %}</title>
   <!-- BOOTSTRAP -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    
    {% block navbar %}
    <nav class="container navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  My Pets
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'pet-list' %}">Pet List</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'pet-create' %}">Add Pet</a></li>                
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Appoinments
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'veterinary-instance-list' %}">My Appoinments</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'veterinary-instance-create' %}">Create Appoinments</a></li>                
                </ul>
              </li>
              {% endif %}
              {% if perms.booking.add_veterinary and perms.booking.add_service %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Clinics
                </a>
              <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'veterinary-create' %}">Add Clinics</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'service-create' %}">Add Services</a></li>                
                </ul>
              </li>
              {% endif %}
              {% if perms.booking.add_doctor and perms.booking.add_specialties %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Doctors
                </a>
              <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'doctor-create' %}">Add Doctors</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'specialties-create' %}">Add Specialties</a></li>                
                </ul>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'veterinarians-list' %}">Clinics</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'doctor-list' %}">Doctors</a>
              </li>
              {% if perms.booking.change_veterinaryinstance %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'appointment' %}">Appointments</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-circle"></i>
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'account_reset_password' %}">Password Reset</a></li>
                  <li><a class="dropdown-item" href="{% url 'account_email' %}">Emails Management</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                  <li><a class="dropdown-item" href="{% url 'account_signup' %}">Signup</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
            <form class="d-flex" action="{% url 'search-results' %}" role="search">
              {% csrf_token %}
              <input class="form-control me-2" name="q" type="search" placeholder="Search Clinics" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% endblock navbar %}
        
    <div class="container">
        {% block content %}
            
        {% endblock content %}
        
        {% block extra_body %}
          
        {% endblock extra_body %}
          
    </div>
</body>
</html>

templates/index.html
{% extends '_base.html' %}


{% block content %}
<h1>Hi,{{ user }}</h1>
<ul>
   <li><strong>available clinics: </strong>{{ available_clinics }}</li>
   <li><strong>available doctors: </strong>{{ available_doctors }}</li>
   {% if user.is_authenticated %}
   <li><strong>appointments: </strong>{{ num_appointments }}</li>
   <li><strong>pets: </strong>{{ num_pets }}</li>
   {% endif %}
</ul>

{% endblock content %}
    